services:
  - type: web
    name: veg-box
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: veg_box_db
          property: connectionString

databases:
  - name: veg_box_db
    plan: free